# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
# - - - - - - - - - - - - - - - - - - - - - -
# Motion sensor associated with light switch
# - - - - - - - - - - - - - - - - - - - - - -
alias: Dining Room Motion Sensor On
initial_state: 'off'
trigger:
  platform: state
  entity_id: binary_sensor.dining_room_motion_sensor
  to: 'on'
action:
  service: script.motion_to_light
  data:
    lights_on_timer: timer.lighting_dining_room
    lights_group: group.dining_room_lights
