10.6.23.10:
  city: none
  country: none
  hostname: 10.6.23.10
  last_authenticated: '2019-06-19 03:43:07'
  previous_authenticated_time: '2019-06-19 02:35:59'
  region: none
10.6.23.9:
  city: none
  country: none
  hostname: 10.6.23.9
  last_authenticated: '2019-06-18 12:51:15'
  previous_authenticated_time: '2019-06-18 12:48:03'
  region: none
172.30.32.2:
  city: none
  country: none
  hostname: hassio_supervisor.hassio
  last_authenticated: '2019-06-19 01:14:01'
  previous_authenticated_time: '2019-06-19 00:23:49'
  region: none
