---
language: python
# Existing Python versions
python:
  - "3.6.4"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./OZW_Log.txt
install:
  - pip3 install homeassistant
  - hass --version

script: hass -c . --script check_config --info all