---
language: python
# Existing Python versions
python:
  - "3.6.4"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./OZW_Log.txt

install:
  - apt install autoconf automake build-essential cmake libass-dev libfreetype6-dev libjpeg-dev libtheora-dev libtool libvorbis-dev libx264-dev pkg-config wget yasm zliblg-dev
  - wget http://ffmpeg.org/releases/ffmpeg-3.2.tar.bz2
  - tar -xjf ffmpeg-3.2.tar.bz2
  - cd ffmpeg-3.2
  - ./configure --disable-static --enable-shared --disable-doc
  - make
  - make install
  - pip3 install --pre homeassistant
  - hass --version

script:
  - hass -c . --script check_config --info all