---
language: python

# Existing Python versions
python:
  - "3.7"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./OZW_Log.txt

install:
  - pip3 install --pre homeassistant
  - hass --version

script:
  - hass -c . --script check_config --info all