# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #

# # ## ## ## ## ## ## ## ## ## ## ## ## ## ##
# #
# #    1. General Settings
# #
# # ## ## ## ## ## ## ## ## ## ## ## ## ## ##

# Basic Information
homeassistant:
  name: Home
  latitude: !secret collings_latitude
  longitude: !secret collings_longitude
  elevation: !secret collings_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret ha_url
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path
  api_password: !secret http_password

# mqtt:
#   broker: !secret ha_base_url
#   broker: localhost
#   port: 1883
#   username: !secret router_username
#   password: !secret router_password
#   discovery: true
#   discovery_prefix: 'hass'

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Device Montitoring
discovery:

# Front-End Settings
config:
conversation:
frontend:
hassio:

#Testing
# More information can be found:
# https://github.com/custom-components/custom_updater/wiki/Installation
custom_updater:
  card_urls:
    - 'https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json'

# ZWave
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 20000
  network_key: !secret zwave_network_key

tts:
  - platform: google

wemo:
  static:
    - !secret ip_wemo_01

#alexa:

# Development Settings
history:
logbook:

alexa:
  intents: !include_dir_named intents/