# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #

# # ## ## ## ## ## ## ## ## ## ## ## ## ## ##
# #
# #    1. General Settings
# #
# # ## ## ## ## ## ## ## ## ## ## ## ## ## ##

# Basic Information
homeassistant:
  name: Home
  latitude: !secret collings_latitude
  longitude: !secret collings_longitude
  elevation: !secret collings_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret ha_url
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path
  api_password: !secret http_password
  ip_ban_enabled: true
  login_attempts_threshold: 10

mqtt:
  broker: localhost
  port: 1883
  username: !secret router_username
  password: !secret router_password

cloud:
  alexa: !include alexa.yaml
config:
frontend:
  javascript_version: 'latest'
hassio:
history:
logbook:
recorder: !include recorder.yaml
logger: !include logger.yaml
discovery:

# Uncomment to use YAML Lovelace
# lovelace:
#   mode: yaml

#Testing
# More information can be found:
# https://github.com/custom-components/custom_updater/wiki/Installation
custom_updater:
  show_installable: false
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

# ZWave
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 20000
  network_key: !secret zwave_network_key

tts:
  - platform: google

wemo:
  static:
    - !secret ip_wemo_01
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

alexa:
automation: !include_dir_list automations/
intent_script: !include_dir_named intents/

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret http_password
  max_retries: 3
  default_measurement: state