name: My House
title: Ryan's Place
views:
#################################################################
#                          LAPTOP VIEW                          #
#################################################################
  - id: 0  # Automatically created id
    title: Laptop View
    icon: mdi:desktop-classic
    panel: true
    cards:
######################################################
#                          Top Bar                #
######################################################
      - id: 3c01ca3a0d7e4c5da1aefba7decd7249  # Automatically created id
        type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - entity: media_player.living_room_tv
                name: Living Room TV
              - entity: sensor.front_door_status
                name: Front Door
######################################################
#                          Main Panel              #
######################################################
          - type: horizontal-stack
            cards:
###########################################
#                          Column 1     #
###########################################
              - type: vertical-stack
                cards:
                  - type: entities
                    entities:
                      - entity: lock.front_door_lock
                        name: Front Door Deadbolt
                      - entity: sensor.front_door_status
                        name: Front Door Status
                      - entity: sensor.front_door_lock_status
                        name: Front Door Lock Status
                      - entity: sensor.front_door_lock_battery
                        name: Front Door Lock Battery
                  - type: entities
                    title: Zestimate
                    entities:
                      - entity: sensor.home_estimate
                        name: Home Estimate
                      - entity: sensor.home_estimate_30_day_change
                        name: 30 Day Change
                      - entity: sensor.home_estimate_last_updated
                        name: Last Updated
                  - type: glance
                    title: Smart Hub Monitors
                    column_width: calc(100% / 5)
                    entities:
                      - entity: sensor.smartthings_hub
                        name: SmartThing
                      - entity: sensor.amazon_dot_upstairs_bathroom
                        name: Shower
                      - entity: sensor.secure_server
                        name: Server
                      - entity: sensor.harmony_hub
                        name: Harmony
                      - entity: sensor.living_room_nest
                        name: Nest
                  - type: glance
                    column_width: calc(100% / 3)
                    entities:
                      - entity: sensor.speedtest_download
                        name: Download
                      - entity: sensor.speedtest_upload
                        name: Upload
                      - entity: sensor.ssl_certificate_expiry
                        name: SSL Expiry
###########################################
#                          Column 2     #
###########################################
              - type: vertical-stack
                cards:
                  - type: picture-elements
                    image: /local/images/floorplan/living_room_portrait_floor_plan.png
                    elements:
                      - type: state-icon
                        tap_action: toggle
                        entity: switch.living_room_light
                        style:
                          top: 15%
                          left: 14.5%
                      - type: state-icon
                        tap_action: toggle
                        entity: switch.living_room_lamp
                        style:
                          top: 89%
                          left: 12%
                      - type: state-icon
                        tap_action: toggle
                        entity: lock.front_door_lock
                        style:
                          top: 97%
                          left: 75%
###########################################
#                          Column 3     #
###########################################
              - type: vertical-stack
                cards:
                  - type: media-control
                    title: Living Room TV
                    entity: media_player.living_room_tv
                  - type: media-control
                    title: Living Room Sonos Surround
                    entity: media_player.living_room_beam
                  - type: picture-elements
                    image: /local/images/foscam/Foscam_remote_small.png
                    elements:
                      - type: icon
                        icon: mdi:home
                        title: Left
                        style:
                          top: 50%
                          left: 10%
                          padding: 20px
                        service: script.turn_on
                        service_data:
                          entity_id: script.foscam_pan_left
                      - type: icon
                        icon: mdi:home
                        title: Right
                        style:
                          top: 50%
                          left: 90%
                          padding: 20px
                        service: script.turn_on
                        service_data:
                          entity_id: script.foscam_pan_right


#################################################################
#                          PHONE VIEW                          #
#################################################################
  - id: 1  # Automatically created id
    title: Phone View
    icon: mdi:cellphone-android
    cards:
      - id: efea9786aa62493d9c27ac825e8e7c16  # Automatically created id
        type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - entity: media_player.living_room_tv
                name: TV
              - entity: sensor.front_door_status
                name: Door
          - type: entities
            entities:
              - entity: lock.front_door_lock
                name: Front Door Deadbolt
              - entity: sensor.front_door_status
                name: Front Door Status
              - entity: sensor.front_door_lock_status
                name: Front Door Lock Status
              - entity: sensor.front_door_lock_battery
                name: Front Door Lock Battery
          - type: glance
            column_width: calc(100% / 4)
            entities:
              - entity: sensor.smartthings_hub
                name: SmartThing
              - entity: sensor.secure_server
                name: Server
              - entity: sensor.harmony_hub
                name: Harmony
              - entity: sensor.living_room_nest
                name: Nest
          - type: glance
            column_width: calc(100% / 3)
            entities:
              - entity: sensor.speedtest_download
                name: Download
              - entity: sensor.speedtest_upload
                name: Upload
              - entity: sensor.ssl_certificate_expiry
                name: SSL Expiry
          - type: picture-elements
            image: /local/images/floorplan/living_room_portrait_floor_plan.png
            elements:
              - type: state-icon
                tap_action: toggle
                entity: switch.living_room_light
                style:
                  top: 15%
                  left: 14.5%
              - type: state-icon
                tap_action: toggle
                entity: switch.living_room_lamp
                style:
                  top: 89%
                  left: 12%
              - type: state-icon
                tap_action: toggle
                entity: lock.front_door_lock
                style:
                  top: 97%
                  left: 75%
          - type: media-control
            title: Living Room TV
            entity: media_player.living_room_tv
          - type: media-control
            title: Living Room Sonos Surround
            entity: media_player.living_room_beam
#################################################################
#                          CAMERA VIEW                          #
#################################################################
  - id: 2  # Automatically created id
    title: Security
    icon: mdi:lock
    cards:
      - id: 2efda9d486cc4ff8b82c4c6ba28c9d96  # Automatically created id
        type: picture-entity
        entity: camera.door_camera
      - id: 6fcb2cc06085451ca383e21873895e40  # Automatically created id
        type: picture-entity
        entity: camera.living_room_camera
#################################################################
#                          WEATHER VIEW                         #
#################################################################
  - id: 3  # Automatically created id
    title: Weather
    icon: mdi:weather-cloudy
    cards:
      - id: ec08fb016be7430ba14197bfb8971407  # Automatically created id
        type: weather-forecast
        entity: weather.dark_sky
      - id: 343b4c8a265b4dd3a6a8081ab296fbd0  # Automatically created id
        type: iframe
        url: https://embed.windy.com/embed2.html
        aspect_ratio: 100%
      - id: d5e7ee01e8464e12b4f23d4306a8beea  # Automatically created id
        type: glance
        title: Indoors
        column_width: calc(100% / 3)
        entities:
          - entity: sensor.living_room_thermostat_temperature
            name: Temperature
          - entity: sensor.living_room_thermostat_target
            name: Target Temperature
          - entity: sensor.living_room_thermostat_humidity
            name: Humidity
