# lovelace_gen
# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
title: Home

# - - - - - - - - - - - - - - - - - - - - - \
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
#  Compact Custom Header 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/
# - - - - - - - - - - - - - - - - - - - - - /
cch:
  background: transparent repeat-x url("/local/images/pattern-small.png")
  background_color: transparent
  default_tab: '0'
  hide_help: true
  hide_config: true
  hide_unused: true
  voice: hide
  exceptions:
    - conditions:
        user: Ryan
      config:
        options: clock
        clock_format: 12
    - conditions:
        user: Surface
      config:
        options: clock
        clock_format: 12
        show_tabs: '0,1,2,3'


# - - - - - - - - - - - - - - - - - - - - - \
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
#  Resources
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/
# - - - - - - - - - - - - - - - - - - - - - /
resources:
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-card-templater/card-templater.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/config-template-card/config-template-card.js
    type: module
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: js
  - url: /community_plugin/flex-table-card/flex-table-card.js
    type: js
  - url: /local/floorplan/floorplan-card.js
    type: module
  - url: /community_plugin/gauge-card/gauge-card.js
    type: js
  - url: /community_plugin/lovelace-github-entity-row/github-entity-row.js
    type: js
  - url: /community_plugin/github-card/github-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    type: js
  - url: /community_plugin/podcast-card/podcast-card.js
    type: module
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js

views:

  - !include lovelace/home_view.yaml
  - !include lovelace/media_view.yaml
  - !include lovelace/automation_view.yaml
  - !include lovelace/climate_view.yaml
  - !include lovelace/security_view.yaml
  - !include lovelace/monitor_view.yaml

# - - - - - - - - - - - - - - - - - - - - - \
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
#  View | Project
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/
# - - - - - - - - - - - - - - - - - - - - - /
  - icon: 'mdi:github-box'
    panel: false
    path: project
    title: PROJECT
    badges: []
    background: center / cover url("/local/images/pattern.png")
    cards:
#     | - - - - - - - - - - - - - - - - - - -
#     |   View | Project | Cards
#     | - - - - - - - - - - - - - - - - - - -
      - type: 'custom:github-card'
        title:  F0123X Github Card
        entities:
          - sensor.hass_config
      - filter:
          include:
            - key: sensor.hass_config.path
              name: Project Name
            - key: sensor.hass_config.latest_commit_message
              name: Latest Commit
            - key: sensor.hass_config.latest_open_issue_url
              name: Latest Issue
            - key: sensor.hass_config.open_issues
              name: Open Issues
        heading_name: Name
        heading_state: Value
        title: Home Assistant Config
        type: 'custom:entity-attributes-card'
      - entities:
          - entity: sensor.f0123x_home_assistant_config_last_build_duration
            name: Last Build Duration
          - entity: sensor.f0123x_home_assistant_config_last_build_finished_at
            name: Last Build Finished At
          - entity: sensor.f0123x_home_assistant_config_last_build_id
            name: Last Build Build ID
          - entity: sensor.f0123x_home_assistant_config_last_build_started_at
            name: Last Build Started At
          - entity: sensor.f0123x_home_assistant_config_last_build_state
            name: Last Build State
          - entity: sensor.f0123x_home_assistant_config_state
            name: State
        show_header_toggle: false
        title: Travis CI
        type: entities
# - - - - - - - - - - - - - - - - - - - - - \
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
#  View | Network
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/
# - - - - - - - - - - - - - - - - - - - - - /
  - icon: 'mdi:security-network'
    panel: false
    path: network
    title: NETWORK
    badges: [ sensor.ssl_certificate_expiry ]
    background: center / cover url("/local/images/pattern.png")
    cards:
#     | - - - - - - - - - - - - - - - - - - -
#     |   View | Network | Cards
#     | - - - - - - - - - - - - - - - - - - -
      - cards:
          - entity: sensor.speedtest_download
            max: 1000
            min: 0
            name: Download (Mbit/s)
            severity:
              green: 400
              red: 100
              yellow: 250
            theme: default
            type: gauge
            unit: ' '
          - entity: sensor.speedtest_upload
            max: 300
            min: 0
            name: Upload (Mbit/s)
            severity:
              green: 250
              red: 0
              yellow: 125
            theme: default
            type: gauge
            unit: ' '
        type: horizontal-stack
      - columns:
          - name: Description
            prop: name
          - name: Wifi Strength
            prop: state
        entities:
          include: sensor.*wifi*strength
        title: Network Strength
        type: 'custom:flex-table-card'
      - clickable: true
        columns:
          - name: Description
            prop: name
          - modify: parseFloat(x)
            name: Signal
            prop: state
        entities:
          include: sensor.*signal
        sort_by: signal
        title: Network Strength 2
        type: 'custom:flex-table-card'

# - - - - - - - - - - - - - - - - - - - - - \
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
#  View | ZWave
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/
# - - - - - - - - - - - - - - - - - - - - - /
  - icon: 'mdi:z-wave'
    panel: false
    path: zwave
    title: ZWAVE
    badges: [ ]
    background: center / cover url("/local/images/pattern.png")
    cards:
#     | - - - - - - - - - - - - - - - - - - -
#     |   View | ZWave | Cards
#     | - - - - - - - - - - - - - - - - - - -
      - cards:
          - entities:
              - zwave.aeotec_zw090_zstick_gen5_us
            show_header_toggle: false
            title: Z-Wave - Aeotec Z-Stick
            type: entities
          - filter:
              include:
                - key: zwave.aeotec_zw090_zstick_gen5_us.friendly_name
                - key: zwave.aeotec_zw090_zstick_gen5_us.manufacturer_name
                - key: zwave.aeotec_zw090_zstick_gen5_us.product_name
                - key: zwave.aeotec_zw090_zstick_gen5_us.is_awake
                - key: zwave.aeotec_zw090_zstick_gen5_us.is_ready
                - key: zwave.aeotec_zw090_zstick_gen5_us.query_stage
                - key: zwave.aeotec_zw090_zstick_gen5_us.node_id
                - key: zwave.aeotec_zw090_zstick_gen5_us.neighbors
            heading_name: Attribute
            heading_state: Value
            type: 'custom:entity-attributes-card'
        type: vertical-stack
      - entities:
          - zwave.aeotec_zw090_zstick_gen5_us
          - zwave.ecolink_doorwindow_sensor
          - zwave.front_door_lock
        show_header_toggle: false
        title: Z-Wave
        type: entities
      - cards:
          - entities:
              - zwave.front_door_lock
            show_header_toggle: false
            title: Z-Wave - Schlage Deadbolt
            type: entities
          - filter:
              include:
                - key: zwave.front_door_lock.friendly_name
                  name: Name
                - key: zwave.front_door_lock.manufacturer_name
                  name: Manufacturer
                - key: zwave.front_door_lock.product_name
                  name: Product
                - key: zwave.front_door_lock.is_awake
                  name: Is Awake
                - key: zwave.front_door_lock.is_ready
                  name: Is Ready
                - key: zwave.front_door_lock.is_failed
                  name: Is Failed
                - key: zwave.front_door_lock.query_stage
                  name: Query Stage
                - key: zwave.front_door_lock.node_id
                  name: Node Id
                - key: zwave.front_door_lock.neighbors
                  name: Neighbors
                - key: zwave.front_door_lock.averageRequestRTT
                - key: zwave.front_door_lock.lastRequestRTT
                - key: zwave.front_door_lock.averageResponseRTT
                - key: zwave.front_door_lock.lastResponseRTT
            heading_name: Attribute
            heading_state: Value
            type: 'custom:entity-attributes-card'
        type: vertical-stack