# lovelace_gen
# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
title: Home
cch: !include lovelace/resources/cch.yaml
resources: !include lovelace/resources/resources.yaml 
views:
  - !include lovelace/home_view.yaml
  - !include lovelace/media_view.yaml
#  - !include lovelace/automation_view.yaml
  - !include lovelace/climate_view.yaml
  - !include lovelace/security_view.yaml
  - !include lovelace/monitor_view.yaml
  - !include lovelace/project_view.yaml
#  - !include lovelace/network_view.yaml
  - !include lovelace/zwave_view.yaml
