name: My House
title: Ryan's Place

# Resources -> css/js/module
# /local/ -> /www/
resources:
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # https://github.com/kalkih/mini-media-player
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  - url: /local/custom-lovelace/mini-media-player-bundle.js?v=0.9.7
    type: module
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # https://github.com/Rocka84/dual-gauge-card
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  - url: /local/custom-lovelace/dual-gauge-card.js
    type: js
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # https://github.com/kuuji/button-card
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  - url: /local/custom-lovelace/button-card.js
    type: module
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # https://github.com/custom-cards/tracker-card
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  - url: /local/custom-lovelace/tracker-card.js?v=0.1.5
    type: js
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # https://github.com/custom-cards/vertical-stack-in-card
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  - url: /local/vertical-stack-in-card.js?v=0.0.9
    type: js

views:
  - !include lovelace/views/home.yaml
#  - !include lovelace/views/security.yaml