# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
# - - - - - - - - - - - - - - - - - - - - - -
# Motion sensor associated with light switch
# 
# - - - - - - - - - - - - - - - - - - - - - -
alias: Office Motion Sensor Off
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.office_motion_sensor
  to: 'off'
  for:
    hours: 0
    minutes: 0
    seconds: 2
action:
  - service: light.turn_off
    entity_id: light.office_multisensor_led
  