# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
# - - - - - - - - - - - - - - - - - - - - - -
# On Start - sets theme and rebuilds
# LoveLace UI
# - - - - - - - - - - - - - - - - - - - - - -
alias: Ryan Leonard Recognized
initial_state: 'on'
trigger:
  platform: event
  event_type: image_processing.face_detect
  event_data:
    name: 'Ryan Leonard'
action:
  service: notify.notify
  data_template:
    message: Ryan Leonard recognized in the living room with probability {{ trigger.event.data.confidence }}
  