# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Front Door Lock                     #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
# - - - - - - - - - - - - - - - - - - - - - -
# Alarm response
# - - - - - - - - - - - - - - - - - - - - - -
alias: Notify on door unlocking
trigger:
  platform: state
  entity_id: lock.front_door_lock
  to: 'unlocked'
condition:
  - condition: state
    entity_id:  binary_sensor.shower
    state:  'on'
action:
  service: notify.notify
  data:
    message: 'Front door has been unlocked'