# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Climate                             #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
##
##    Nest Climate Control
##
## ## ## ## ## ## ## ## ## ## ## ## ## ## ###

- platform: zestimate
  api_key: !secret zestimate_api_key
  zpid:
    - !secret zestimate_zpid

- platform: cert_expiry
  host: !secret ha_base_url

- platform: speedtest
  monitored_conditions:
    - download
    - upload

- platform: template
  sensors:
    home_estimate: 
      friendly_name: Home Estimate
      value_template: '{{ "${:,.0f}".format(states.sensor.zestimate.attributes.valuation_range_high) }}'
      entity_id: sensor.zestimate
    home_estimate_30_day_change: 
      friendly_name: Home Estimate 30 Day Change
      value_template: '{{ "${:,.0f}".format(states.sensor.zestimate.attributes.amount_change_30_days) }}'
      entity_id: sensor.zestimate
    home_estimate_last_updated: 
      friendly_name: Home Estimate Last Updated
      value_template: '{{ states.sensor.zestimate.attributes.amount_last_updated }}'
      entity_id: sensor.zestimate
    amazon_echo:
      friendly_name: Amazon Echo
      value_template: >-
          {%- if is_state("device_tracker.amazon_echo", "home") %}
              Connected
          {% else %}
              Not Connected
          {%- endif %}
    amazon_dot:
      friendly_name: Amazon Dot
      value_template: >-
          {%- if is_state("device_tracker.amazon_dot", "home") %}
              Connected
          {% else %}
              Not Connected
          {%- endif %}
    secure_server:
      friendly_name: Secure Server
      value_template: >-
          {%- if is_state("device_tracker.secure_server", "home") %}
              Connected
          {% else %}
              Not Connected
          {%- endif %}
    harmony_hub:
      friendly_name: Harmony Hub
      value_template: >-
          {%- if is_state("device_tracker.harmony_hub", "home") %}
              Connected
          {% else %}
              Not Connected
          {%- endif %}

# - platform: ups
#   username: !secret ups_user
#   password: !secret ups_pass