# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
# - - - - - - - - - - - - - - - - - - - - - -
# On Start - Hassio Backup
# LoveLace UI
# - - - - - - - - - - - - - - - - - - - - - -
alias: Daily snapshot clean up
initial_state: 'on'
trigger: 
  platform: time
  at: '06:00:00'
condition:
action:
  - service: clean_up_snapshots_service.clean_up