# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
alias: Reboot Scenario
trigger:
  platform: state
  entity_id: zwave.front_door_lock
  to: "initializing"
  for: "00:03:00"
action:
  - service: notify.notify
    data:
      message: ZWave isn't working.