substitutions:
  devicenumber: '10'
  location: 'Server Rack'
  location_id: 'server_rack'

esphome:
  name: esp8266_${devicenumber}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 115200

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: D7
    model: DHT11
    temperature:
      name: ${location} Temperature
      accuracy_decimals: 1
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      on_value:
        then:
          - light.toggle:
              id: ${location_id}_multisensor_led
      on_value_range:
        - below: 75
          then: 
            - light.turn_on: 
                id: ${location_id}_multisensor_led
                brightness: 100%
                red: 0%
                green: 100%
                blue: 0%
        - below: 95
          above: 75
          then:
            - light.turn_on: 
                id: ${location_id}_multisensor_led
                brightness: 100%
                red: 100%
                green: 100%
                blue: 0%
        - above: 95
          then: 
            - light.turn_on: 
                id: ${location_id}_multisensor_led
                brightness: 100%
                red: 100%
                green: 0%
                blue: 0%
    humidity:
      name: ${location} Humidity
      accuracy_decimals: 1
    update_interval: 2s
  - platform: wifi_signal
    name: ${location} WiFi Strength
    update_interval: 60s


output:
  - platform: esp8266_pwm
    pin: D1
    id: gpio_d1
  - platform: esp8266_pwm
    pin: D2
    id: gpio_d2
  - platform: esp8266_pwm
    pin: D3
    id: gpio_d3

light:
  - platform: rgb
    name: ${location} Multisensor LED
    id: ${location_id}_multisensor_led
    red: gpio_d1
    green: gpio_d2
    blue: gpio_d3