substitutions:
  devicenumber: '06'
  location: 'Kitchen'

esphome:
  name: esp8266_${devicenumber}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable logging
logger:
  baud_rate: 115200

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: D5
    name: ${location} Motion Sensor
    device_class: motion

sensor:
  - platform: dht
    pin: D7
    model: DHT11
    temperature:
      name: ${location} Temperature
      accuracy_decimals: 1
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: ${location} Humidity
      accuracy_decimals: 1
    update_interval: 60s
  - platform: wifi_signal
    name: ${location} WiFi Strength
    update_interval: 60s
