# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Admin Panels                        #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
frontend:
  themes:
    darkcyan:
    # Main colors that can be changed
      primary-color: "#00bcd4"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#4e4e4e"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      paper-listbox-color: "#FFFFFF"      
      primary-background-color: "#303030"
      primary-text-color: "#cfcfcf"      
      secondary-background-color: "#2b2b2b"
      secondary-text-color: "#04a7bc"
    # Colors based on variables, see above
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#var(--paper-item-icon-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"     
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"

# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Admin Panels                        #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
panel_iframe:
  cloud9_ide:
    title: Cloud9 IDE
    icon: mdi:cloud-braces
    url: !secret add_on_cloud9ide_url
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret add_on_configurator_url
  log_viewer:
    title: Log Viewer
    icon: mdi:file-alert
    url: !secret add_on_logviewer_url

# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Recorder                             #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
recorder:
  purge_interval: 1
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.home_eta

# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Logger                              #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
logger:
  default: debug
  logs:
    async_upnp_client: info
    glances: error
    haffmpeg.core: info
    homeassistant: debug
    homeassistant.components.http.auth: critical
    homeassistant.components.http.view: error  
    homeassistant.components: info
    homeassistant.components.device_tracker.netgear: error
    homeassistant.components.media_player: error
    homeassistant.components.websocket_api: error
    homeassistant.components.zwave.util: error
    homeassistant.components.recorder: critical
    homeassistant.core: critical
    homeassistant.components.mqtt: error
    homeassistant.helpers.storage: critical
    homeassistant.helpers.restore_state: info
    homeassistant.util.json: error
    hbmqtt: debug
    hbmqtt.mqtt: error
    hbmqtt.broker: error
    pyHS100: error
    amcrest.http: error
    nest.nest: error
    suds: error
    libopenzwave: error
    openzwave: error
    pynetgear: error
    pyupdate.ha_custom.custom_components: info
    sseclient: info
    transitions.core: error
    passlib.registry: error

# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Device Trackers                     #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
device_tracker:
  - platform: netgear
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password

notify:
  - platform: pushbullet
    name: Notify
    api_key: !secret pushbullet_api_key


# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# UI Lovelace Update Command          #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'

# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Glances                             #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
sensor:
  - platform: glances
    name: Glances
    version: 3
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
      - 'cpu_temp'
      - 'docker_active'
      - 'docker_cpu_use'
      - 'docker_memory_use'

# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Starting Automations                #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
script:
  on_start:
    alias: On Start
    sequence:
      - service: frontend.set_theme
        data:
          name: darkcyan
      - service: shell_command.lovelace_gen


# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Starting Automations                #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
automation:
  - alias: 'Set theme and rebuild lovelace ui'
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.turn_on
        entity_id: script.on_start
