# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Indoor Climate                      #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
homeassistant:
  customize_glob:
    "sensor.*_temperature":
      device_class: temperature
      unit_of_measurement: '°F'
    "sensor.*_humidity":
      device_class: humidity
      unit_of_measurement: '%'
    "sensor.*_thermostat_target":
      device_class: temperature
      unit_of_measurement: '°F'


weather:
  - platform: darksky
    api_key: !secret forecast_api_key

sensor:
  - platform: nest
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'humidity'
      - 'operation_mode'

  - platform: template
    sensors:
      weather_temperature:
        friendly_name: Weather Temperature
        value_template: '{{ states.weather.dark_sky.attributes.temperature }}'
        entity_id: weather.dark_sky
      weather_humidity:
        friendly_name: Weather Humidity
        value_template: '{{ states.weather.dark_sky.attributes.humidity }}'
        entity_id: weather.dark_sky
# - - - - - - - - - - - - - - - - - - - - - -
# ESP8266 NodeMCU with DHT11 sensor
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Office Temperature
    state_topic: 'hass/esp8266_02'
    qos: 0
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    name: Office Humidity
    state_topic: 'hass/esp8266_02'
    qos: 0
    value_template: '{{ value_json.humidity }}'
