# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Downstairs Bathroom                 #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # # # # # #
#             Switches
# # # # # # # # # # # # # # # # # # # # # # #
switch:
# - - - - - - - - - - - - - - - - - - - - - -
# Washer
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: tplink
    name: Washer
    host: !secret ip_tplink_h110_05
    icon: mdi:tumble-dryer

# # # # # # # # # # # # # # # # # # # # # # #
#             Sensors
# # # # # # # # # # # # # # # # # # # # # # #
sensor:
  - platform: template
    sensors:
# - - - - - - - - - - - - - - - - - - - - - -
# Washer Sensors
# - - - - - - - - - - - - - - - - - - - - - -
      washer_amps:
        friendly_name: Washer Amps
        value_template: '{{ states.switch.washer.attributes.current_a }}'
        unit_of_measurement: 'Amps'
        entity_id: switch.washer
      washer_power:
        friendly_name: Washer Power
        value_template: '{{ states.switch.washer.attributes.current_power_w }}'
        unit_of_measurement: 'W'
        entity_id: switch.washer
      washer_voltage:
        friendly_name: Washer Voltage
        value_template: '{{ states.switch.washer.attributes.voltage }}'
        unit_of_measurement: 'V'
        entity_id: switch.washer
binary_sensor:
  - platform: template
    sensors:
      washer:
        friendly_name: "Washer"
        delay_off:
          minutes: 5
        value_template: "{{ states('states.switch.washer.attributes.current_power_w')|float > 0 }}"
        device_class: vibration