# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #

notify:
  - platform: pushbullet
    name: Notify
    api_key: !secret pushbullet_api_key

# # # # # # # # # # # # # # # # # # # # # # #
#             Sensors
# # # # # # # # # # # # # # # # # # # # # # #
sensor:
# - - - - - - - - - - - - - - - - - - - - - -
# Internet speed
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: speedtest
    monitored_conditions:
      - download
      - upload
# - - - - - - - - - - - - - - - - - - - - - -
# Zestimate
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: zestimate
    api_key: !secret zestimate_api_key
    zpid:
      - !secret zestimate_zpid
# - - - - - - - - - - - - - - - - - - - - - -
# Pi Hole Sensor
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: pi_hole
    host: !secret ip_pi_hole
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today

# - - - - - - - - - - - - - - - - - - - - - -
# MQTT Status
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: MQTT Status
    state_topic: 'hass/status'
    qos: 0
    icon: mdi:home
# - - - - - - - - - - - - - - - - - - - - - -
# Trash reminder status
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Trash Reminder Status
    state_topic: 'hass/automation/reminders/trash/status'
    qos: 0
    icon: mdi:trash-can

# # # # # # # # # # # # # # # # # # # # # # #
#         Binary Sensors
# # # # # # # # # # # # # # # # # # # # # # #
binary_sensor:
# - - - - - - - - - - - - - - - - - - - - - -
# Trash Day
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: workday
    name: Trash Day
    country: US
    workdays: [thu]

# # # # # # # # # # # # # # # # # # # # # # #
#         Switches
# # # # # # # # # # # # # # # # # # # # # # #
switch:
# - - - - - - - - - - - - - - - - - - - - - -
# Trash Day Reminder 1
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: 'Trash Reminder 5 PM'
    state_topic: 'hass/automation/reminders/trash/5pm'
    command_topic: 'hass/automation/reminders/trash/5pm'
    availability_topic: 'hass/automation/reminders/trash/status'
    state_on: 'on'
    state_off: 'off'
    payload_on: 'on'
    payload_off: 'off'
    qos: 0
    retain: true
    icon: mdi:trash-can
# - - - - - - - - - - - - - - - - - - - - - -
# Trash Day Reminder 2
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: 'Trash Reminder 7 PM'
    state_topic: 'hass/automation/reminders/trash/7pm'
    command_topic: 'hass/automation/reminders/trash/7pm'
    availability_topic: 'hass/automation/reminders/trash/status'
    state_on: 'on'
    state_off: 'off'
    payload_on: 'on'
    payload_off: 'off'
    qos: 0
    retain: true
    icon: mdi:trash-can
# - - - - - - - - - - - - - - - - - - - - - -
# Trash Day Reminder 3
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: 'Trash Reminder 9 PM'
    state_topic: 'hass/automation/reminders/trash/9pm'
    command_topic: 'hass/automation/reminders/trash/9pm'
    availability_topic: 'hass/automation/reminders/trash/status'
    state_on: 'on'
    state_off: 'off'
    payload_on: 'on'
    payload_off: 'off'
    qos: 0
    retain: true
    icon: mdi:trash-can
# - - - - - - - - - - - - - - - - - - - - - -
# Trash Day Reminder 4
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: 'Trash Reminder 10 PM'
    state_topic: 'hass/automation/reminders/trash/10pm'
    command_topic: 'hass/automation/reminders/trash/10pm'
    availability_topic: 'hass/automation/reminders/trash/status'
    state_on: 'on'
    state_off: 'off'
    payload_on: 'on'
    payload_off: 'off'
    qos: 0
    retain: true
    icon: mdi:trash-can