# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Living Room                         #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # # # # # #
#         Living Room TV Sensor
# # # # # # # # # # # # # # # # # # # # # # #
sensor:
  - platform: template
    sensors:
      living_room_tv:
        friendly_name: Living Room TV
        value_template: "{{ states.remote.living_room.attributes.current_activity }}"
        entity_id: remote.living_room

# # # # # # # # # # # # # # # # # # # # # # #
#             Sonos Speakers
# # # # # # # # # # # # # # # # # # # # # # #
sonos:
  media_player:
    interface_addr: 192.168.1.1
    hosts:
      - 192.168.1.42
      - 192.168.1.41
      - 192.168.1.40

# # # # # # # # # # # # # # # # # # # # # # #
#             Remotes
# # # # # # # # # # # # # # # # # # # # # # #
remote:
  - platform: harmony
    name: Living Room
    host: !secret ip_logitech_harmony_01

# # # # # # # # # # # # # # # # # # # # # # #
#             Switches
# # # # # # # # # # # # # # # # # # # # # # #
switch:
# - - - - - - - - - - - - - - - - - - - - - -
# Lighting
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: tplink
    name: Living Room Light
    host: !secret ip_tplink_h100_01
    icon: mdi:lightbulb
  - platform: tplink
    name: Living Room Lamp
    host: !secret ip_tplink_h100_02
    icon: mdi:lightbulb
# - - - - - - - - - - - - - - - - - - - - - -
# Template switches
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: template
    switches:
      living_room_tv:
        friendly_name: Living Room TV
        value_template: "{{ is_state('sensor.living_room_tv', 'Watch Smart TV') }}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.living_room
          data:
            activity: 'Watch Smart TV'
        turn_off:
          service: remote.turn_off
          entity_id: remote.living_room
          data:
            activity: 'Watch Smart TV'

# # # # # # # # # # # # # # # # # # # # # # #
#             Groups
# # # # # # # # # # # # # # # # # # # # # # #
group:
  living_room_lights:
    name: Living Room Lights
    entities:
      - switch.living_room_light
      - switch.living_room_lamp

# # # # # # # # # # # # # # # # # # # # # # #
#             Scripts
# # # # # # # # # # # # # # # # # # # # # # #
script:
# - - - - - - - - - - - - - - - - - - - - - -
# Turn on TV
# - - - - - - - - - - - - - - - - - - - - - -
  turn_on_tv:
    alias: Turn On TV
    sequence:
      - service: remote.send_command
        data:
          command:
          - PowerOn
          - Home
          delay_secs: 0.5
          device: 49552536
          entity_id: remote.living_room
# - - - - - - - - - - - - - - - - - - - - - -
# Turn off TV
# - - - - - - - - - - - - - - - - - - - - - -
  turn_off_tv:
    alias: Turn Off TV
    sequence:
      - service: remote.send_command
        data:
          command:
          - PowerOff
          delay_secs: 0.5
          device: 49552536
          entity_id: remote.living_room

# # # # # # # # # # # # # # # # # # # # # # #
#             Media Players
# # # # # # # # # # # # # # # # # # # # # # #
media_player:
  - platform: universal
    name: Living Room TV
    children:
      - media_player.living_room_sonos
    commands:
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.living_room_tv
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.living_room_tv
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.living_room_sonos
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.living_room_sonos
      volume_mute:
        service: media_player.volume_mute
        data_template:
          entity_id: media_player.living_room_sonos
          is_volume_muted: '{{ is_volume_muted }}'
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_sonos
          volume_level: '{{ volume_level }}'
    attributes:
      is_volume_muted: media_player.living_room_sonos|is_volume_muted
      volume_level: media_player.living_room_sonos|volume_level
      state: switch.living_room_tv