# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Location                            #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
zone:
  - name: home
    latitude: !secret collings_latitude
    longitude: !secret collings_longitude
    radius: 75
    icon: mdi:home-map-marker

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 300
    waypoints: true
    mqtt_topic: "hass/mobile/ryan"
    events_only: true
  - platform: netgear
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password

sensor:
  - platform: mqtt
    name: Pixel Battery
    state_topic: 'hass/mobile/ryan/battery'
    qos: 0
    availability_topic: 'hass/status'

automation:
  - alias: HA Presence Detection
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.ryans_pixel
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 0
        seconds: 30
    action:
      service: notify.notify
      data:
        message: "Sent from home assistant based on state change"
        title: "Method 1"