# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Location                            #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #
zone:
  - name: Home
    latitude: !secret collings_latitude
    longitude: !secret collings_longitude
    radius: 75
    icon: mdi:home-map-marker

owntracks:
  max_gps_accuracy: 10000
  waypoints: true
  mqtt_topic: "hass/location/#"
  region_mapping: 
    home: home

device_tracker:
  # - platform: owntracks
  #   max_gps_accuracy: 10000
  #   waypoints: true
  #   mqtt_topic: "hass/mobile/ryan"
  # - platform: owntracks
  #   max_gps_accuracy: 10000
  #   waypoints: true
  #   mqtt_topic: "hass/tablet/ryan"
  # - platform: traccar
  #   host: localhost
  #   # host: a0d7b954-traccar
  #   #port: 8072
  #   username: !secret traccar_username
  #   password: !secret traccar_password
  - platform: ddwrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    interval_seconds: 30
    consider_home: 180
    track_new_devices: yes

sensor:
  - platform: mqtt
    name: Pixel Battery
    state_topic: 'hass/mobile/ryan/battery'
    qos: 0
    availability_topic: 'hass/status'
  - platform: mqtt
    name: Wall Mount Battery
    state_topic: 'hass/tablet/ryan/battery'
    qos: 0
    availability_topic: 'hass/status'