# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Package                             #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #

##########################################################
## Trash Pickup Reminder
##########################################################

# input_select:
#   trash_pickup_day:
#     name: Trash Pickup Day
#     options:
#     - Monday
#     - Tuesday
#     - Wednesday
#     - Thursday
#     - Friday
#     - Saturday
#     - Sunday
#     - unknown
#     icon: mdi:trash-can

binary_sensor:
  - platform: workday
    name: Trash Day
    country: US
    workdays: [thu]

# input_boolean:
#   trash_reminder_5_pm:
#     name: Trash Reminder 5 PM
#     initial: on
#     icon: mdi:trash-can
#   trash_reminder_7_pm:
#     name: Trash Reminder 7 PM
#     initial: on
#     icon: mdi:trash-can
#   trash_reminder_9_pm:
#     name: Trash Reminder 9 PM
#     initial: on
#     icon: mdi:trash-can
#   trash_reminder_10_pm:
#     name: Trash Reminder 10 PM
#     initial: on
#     icon: mdi:trash-can



###############################################################################
# Trash  - Pickup schedule is EVERY week.
# Set the day to a day before the actual day leaving time for reminders
###############################################################################
# sensor:
#   - platform: template
#     sensors:
#       trash_day:
#         value_template: >-
#           {% set year = states.sensor.date__time.state.split(',')[0].split('-')[0] %}
#           {% set month = states.sensor.date__time.state.split(',')[0].split('-')[1] %}
#           {% set date = states.sensor.date__time.state.split(',')[0].split('-')[2] %}
#           {% set today = strptime(year ~ '-' ~ month ~ '-' ~ date , '%Y-%m-%d') %}
#           {%- set pickupDay = 'Thursday' | lower -%} 
#           {%- if as_timestamp(today)| timestamp_custom('%A', true) | lower == pickupDay -%}
#             yes
#           {%- else -%}
#             no
#           {%- endif -%}


# script:
#   trash_reminder:
#     alias: Trash Reminder
#     sequence:
#       - service: script.sonos_say
#         data:
#           sonos_entity: media_player.living_room_beam
#           volume: 0.5
#           message: 'Please remember to take out the trash, trash day is tomorrow!'
#           delay: '00:00:05'

# automation:
# - alias: Reminder To Take Out The Trash
#   trigger:
#     - platform: time
#       at: '17:00:00'
#     - platform: time
#       at: '19:00:00'
#     - platform: time
#       at: '20:00:00'
#     - platform: time
#       at: '21:00:00'
#   condition:
#     - condition: template
#       value_template: '{{ states.input_boolean.trash_reminder.state == "on" }}'
#     - condition: state
#       entity_id: sensor.trash_day
#       state: 'yes'
#     - condition: state
#       entity_id: device_tracker.ryans_pixel
#       state: 'home'
#   action:
#     - service: script.turn_on
#       entity_id: script.trash_reminder