# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Security                            #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # # # # # #
#             Alarm Control
# # # # # # # # # # # # # # # # # # # # # # #
alarm_control_panel:
# - - - - - - - - - - - - - - - - - - - - - -
# Alarm Control Panel
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: manual
    name: Home Alarm
    code: !secret home_alarm_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    triggered:
      pending_time: 0

# # # # # # # # # # # # # # # # # # # # # # #
#             Automation
# # # # # # # # # # # # # # # # # # # # # # #
automation:
# - - - - - - - - - - - - - - - - - - - - - -
# armed_home trigger
# - - - - - - - - - - - - - - - - - - - - - -
  - alias: Security - Trigger alarm while armed home
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door
      - platform: state
        entity_id: binary_sensor.basement_door
      - platform: state
        entity_id: binary_sensor.front_door
      - platform: state
        entity_id: binary_sensor.front_door_camera
      - platform: state
        entity_id: binary_sensor.front_door_lock
      - platform: state
        entity_id: binary_sensor.front_left_window
      - platform: state
        entity_id: binary_sensor.front_right_window
      - platform: state
        entity_id: binary_sensor.washer_leak_sensor
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
# - - - - - - - - - - - - - - - - - - - - - -
# armed_away trigger
# - - - - - - - - - - - - - - - - - - - - - -
  - alias: Security - Trigger alarm while armed away
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door
      - platform: state
        entity_id: binary_sensor.basement_door
      - platform: state
        entity_id: binary_sensor.front_door
      - platform: state
        entity_id: binary_sensor.front_door_camera
      - platform: state
        entity_id: binary_sensor.front_door_lock
      - platform: state
        entity_id: binary_sensor.front_left_window
      - platform: state
        entity_id: binary_sensor.front_right_window
      - platform: state
        entity_id: binary_sensor.washer_leak_sensor
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm

# - - - - - - - - - - - - - - - - - - - - - -
# Alarm response
# - - - - - - - - - - - - - - - - - - - - - -
  - alias: Security - Alarm triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: 'triggered'
    action:
      - service: notify.notify
        data:
          message: 'ALARM! The alarm has been triggered'

# - - - - - - - - - - - - - - - - - - - - - -
# Alarm response
# - - - - - - - - - - - - - - - - - - - - - -
  - alias: Notify on door unlocking
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_lock
        to: 'unlocked'
    action:
      - service: notify.notify
        data:
          message: 'Front door has been unlocked'

# # # # # # # # # # # # # # # # # # # # # # #
#                 Cameras
# # # # # # # # # # # # # # # # # # # # # # #
# Front Door
# - - - - - - - - - - - - - - - - - - - - - -
amcrest:
- host: !secret ip_amcrest_camera_01
  name: Front Door Camera
  username: !secret router_username
  password: !secret router_password
  stream_source: mjpeg
  sensors:
    - motion_detector
  resolution: low

camera:
  - name: Front Door Camera
    platform: amcrest

# # # # # # # # # # # # # # # # # # # # # # #
#             Binary Sensors
# # # # # # # # # # # # # # # # # # # # # # #
binary_sensor:
# - - - - - - - - - - - - - - - - - - - - - -
# Door Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Back Door
    state_topic: 'hass/Back Door Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
  - platform: mqtt
    name: Basement Door
    state_topic: 'hass/Basement Door Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
# - - - - - - - - - - - - - - - - - - - - - -
# Window Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Front Right Window
    state_topic: 'hass/Front Right Window Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
  - platform: mqtt
    name: Front Left Window
    state_topic: 'hass/Front Left Window Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
# - - - - - - - - - - - - - - - - - - - - - -
# Leak Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Washer Leak Sensor
    state_topic: 'hass/Washer Leak Sensor/water/state'
    qos: 0
    payload_on: 'wet'
    payload_off: 'dry'
# - - - - - - - - - - - - - - - - - - - - - -
# Template Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: template
    sensors:
      front_door:
        friendly_name: Front Door
        value_template: "{{ not is_state('sensor.ecolink_doorwindow_sensor_access_control', '23') }}"
        entity_id: sensor.ecolink_doorwindow_sensor_access_control
      front_door_camera:
        friendly_name: Front Door Camera
        value_template: "{{ is_state('sensor.front_door_camera_motion_detected', 'True') }}"
        entity_id: sensor.front_door_camera_motion_detected
        delay_on:
          seconds: 20
      front_door_lock:
        friendly_name: Front Door Lock
        value_template: "{{ is_state('lock.front_door_lock', 'unlocked') }}"
        entity_id: lock.front_door_lock

# # # # # # # # # # # # # # # # # # # # # # #
#               Sensors
# # # # # # # # # # # # # # # # # # # # # # #
sensor:

# - - - - - - - - - - - - - - - - - - - - - -
# Battery Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Back Door Battery
    state_topic: 'hass/Back Door Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Basement Door Battery
    state_topic: 'hass/Basement Door Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Front Right Window Battery
    state_topic: 'hass/Front Right Window Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Front Left Window Battery
    state_topic: 'hass/Front Left Window Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Washer Leak Sensor Battery
    state_topic: 'hass/Washer Leak Sensor/battery/state'
    qos: 0

# - - - - - - - - - - - - - - - - - - - - - -
# Uptime
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: uptime
    name: Time Online
    unit_of_measurement: hours

# - - - - - - - - - - - - - - - - - - - - - -
# Template Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: template
    sensors:
      front_door_battery:
        friendly_name: Front Door Battery
        value_template: '{{ states.zwave.ecolink_doorwindow_sensor.attributes.battery_level }}'
        entity_id: zwave.ecolink_doorwindow_sensor
      front_door_lock_battery:
        friendly_name: Front Door Lock Battery
        value_template: '{{ states.zwave.front_door_lock.attributes.battery_level }}'
        entity_id: zwave.front_door_lock

# # # # # # # # # # # # # # # # # # # # # # #
#               Switches
# # # # # # # # # # # # # # # # # # # # # # #
switch:
  - platform: mqtt
    name: Front Door Lock Automation
    state_topic: "hass/automation/locks/front-door"
    command_topic: "hass/automation/locks/front-door"
    qos: 0
    retain: true