# # # # # # # # # # # # # # # # # # # # # # #
#                     #                     #
#                   #   #                   #
#                 #       #                 #
#               #           #               #
#             #     Home      #             #
#           #                   #           #
#         # # #   Assistant   # # #         #
#             #               #             #
#             #               #             #
#             #               #             #
#             #               #             #
#             # # # # # # # # #             #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #
#
# # # # # # # # # # # # # # # # # # # # # # #
#                                        #   
# Security                            #      
#                                        #   
# # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # # # # # #
#             Alarm Control
# # # # # # # # # # # # # # # # # # # # # # #
alarm_control_panel:
# - - - - - - - - - - - - - - - - - - - - - -
# Alarm Control Panel
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: manual
    name: Home Alarm
    code: !secret home_alarm_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    triggered:
      pending_time: 0

# # # # # # # # # # # # # # # # # # # # # # #
#                 Cameras
# # # # # # # # # # # # # # # # # # # # # # #
camera:
  - platform: generic
    name: Front Door Camera
    still_image_url: !secret front_door_camera
  - platform: generic
    name: Living Room Camera
    still_image_url: !secret living_room_camera
  - platform: generic
    name: Office Camera
    still_image_url: !secret office_camera
  - platform: generic
    name: Surface Pro Camera
    still_image_url: !secret surface_pro_camera


# # # # # # # # # # # # # # # # # # # # # # #
#             Binary Sensors
# # # # # # # # # # # # # # # # # # # # # # #
binary_sensor:
# - - - - - - - - - - - - - - - - - - - - - -
# Door Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Back Door
    state_topic: 'hass/Back Door Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
  - platform: mqtt
    name: Basement Door
    state_topic: 'hass/Basement Door Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
# - - - - - - - - - - - - - - - - - - - - - -
# Window Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Front Right Window
    state_topic: 'hass/Front Right Window Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
  - platform: mqtt
    name: Front Left Window
    state_topic: 'hass/Front Left Window Sensor/contact/state'
    qos: 0
    payload_on: 'open'
    payload_off: 'closed'
# - - - - - - - - - - - - - - - - - - - - - -
# Leak Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Washer Leak Sensor
    state_topic: 'hass/Washer Leak Sensor/water/state'
    qos: 0
    payload_on: 'wet'
    payload_off: 'dry'
# - - - - - - - - - - - - - - - - - - - - - -
# Smoke Detectors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Office Smoke Detector
    state_topic: 'hass/Living Room Smoke Detector/smoke/state'
    qos: 0
    payload_on: 'detected'
    payload_off: 'clear'
# - - - - - - - - - - - - - - - - - - - - - -
# Template Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: template
    sensors:
      front_door:
        friendly_name: Front Door
        value_template: "{{ not is_state('sensor.ecolink_doorwindow_sensor_access_control', '23') }}"
        entity_id: sensor.ecolink_doorwindow_sensor_access_control
      front_door_lock:
        friendly_name: Front Door Lock
        value_template: "{{ is_state('lock.front_door_lock', 'unlocked') }}"
        entity_id: lock.front_door_lock

# # # # # # # # # # # # # # # # # # # # # # #
#               Sensors
# # # # # # # # # # # # # # # # # # # # # # #
sensor:
# - - - - - - - - - - - - - - - - - - - - - -
# Battery Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: mqtt
    name: Back Door Battery
    state_topic: 'hass/Back Door Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Basement Door Battery
    state_topic: 'hass/Basement Door Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Front Right Window Battery
    state_topic: 'hass/Front Right Window Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Front Left Window Battery
    state_topic: 'hass/Front Left Window Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Washer Leak Sensor Battery
    state_topic: 'hass/Washer Leak Sensor/battery/state'
    qos: 0
  - platform: mqtt
    name: Office Smoke Detector Battery
    state_topic: 'hass/Living Room Smoke Detector/battery/state'
    qos: 0

# - - - - - - - - - - - - - - - - - - - - - -
# Template Sensors
# - - - - - - - - - - - - - - - - - - - - - -
  - platform: template
    sensors:
      front_door_battery:
        friendly_name: Front Door Battery
        value_template: '{{ states.zwave.ecolink_doorwindow_sensor.attributes.battery_level }}'
        entity_id: zwave.ecolink_doorwindow_sensor
      front_door_lock_battery:
        friendly_name: Front Door Lock Battery
        value_template: '{{ states.zwave.front_door_lock.attributes.battery_level }}'
        entity_id: zwave.front_door_lock

# # # # # # # # # # # # # # # # # # # # # # #
#               Switches
# # # # # # # # # # # # # # # # # # # # # # #
switch:
  - platform: mqtt
    name: Front Door Lock Automation
    state_topic: "hass/automation/locks/front-door"
    command_topic: "hass/automation/locks/front-door"
    qos: 0
    retain: true